server:
  port: 8090
spring1:
  jdbc:
    datasource:
      username: test
      url: test
      password: test
      driver-class-name: test
management:
  endpoints:
    web:
      exposure:
        include: '*'  # 对外暴露的访问入口 , 默认是/health和/info
      base-path: /monitor # 默认是actuator
  endpoint:
    health:
      show-details: ALWAYS	# 显示所有健康状态
  server:
    port: 9997
spring:
  boot:
    admin:
      client:
        url: http://localhost:8769/